services:
  # 1. FastAPI Server
  prism-app:
    build: .
    container_name: prism-gateway
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OLLAMA_API_BASE=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    networks:
      - prism-network


  # 2. 비동기 작업용 큐 (나중에 로그 저장용으로 사용)
  redis:
    image: redis:alpine
    container_name: prism-redis
    ports:
      - "6379:6379"
    networks:
      - prism-network

  # 3. 데이터 수집기 (Prometheus)
  prometheus:
    image: prom/prometheus:latest
    container_name: prism-prometheus
    ports:
      - "9090:9090"
    volumes:
      # 아까 만든 설정 파일을 컨테이너 안으로 연결(Mount)
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prism-network

  # 4. 데이터 시각화 (Grafana)
  grafana:
    image: grafana/grafana:latest
    container_name: prism-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # 초기 비번 설정
    depends_on:
      - prometheus
    networks:
      - prism-network

  # 5. FrontEnd Service
  prism-frontend:
    build: .
    container_name: prism-frontend
    # 이미지가 켜지면 실행할 명령어
    command: streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501" # 웹 브라우저 접속 포트
    depends_on:
      - prism-app # 백엔드가 켜져야 나도 켜짐
    networks:
      - prism-network

# 5. 전용 네트워크 생성 (이 안에서 서로 이름으로 통신함)
networks:
  prism-network:
    driver: bridge