global:
  scrape_interval: 5s # 5초마다 긁어오기 (실시간성 확보)

scrape_configs:
  - job_name: 'fastapi-backend'
    metrics_path: '/metrics'
    static_configs:
      # Docker Network 내부의 서비스 이름(prism-gateway)으로 접속
      - targets: ['prism-gateway:8000']